[project]
requires-python = ">=3.8,<4"
dependencies = [
    "click >= 7.0.0",
    "cloudpickle >= 1.5.0",
    "dask[dataframe] >= 2021.10.0",
    "distributed >= 2021.10.0",
    "holidays >= 0.13",
    "numpy >= 1.21.0",
    "pandas >= 1.3.0",
    "psutil >= 5.6.6",
    "scipy >= 1.3.3",
    "tqdm >= 4.32.0",
    "woodwork >= 0.16.2",
]

[project.optional-dependencies]
test = [
    "boto3 >= 1.17.46",
    "composeml >= 0.8.0",
    "graphviz >= 0.8.4",
    "moto[all] >= 3.0.7",
    "pip >= 21.3.1",
    "pyarrow >= 3.0.0",
    "pympler >= 0.8",
    "pytest >= 7.1.2",
    "pytest-cov >= 3.0.0",
    "pytest-xdist >= 2.5.0",
    "smart-open >= 5.0.0",
    "urllib3 >= 1.26.5",
]
