name: 'Create Feedstock Meta YAML'
description: 'Create meta.yaml for a conda feedstock based on a PyPI version'
inputs:
  project:
    required: true
  pypi_version:
    required: true
  setup_cfg_filepath:
    required: true
  meta_yaml_filepath:
    required: true
  add_to_run_requirements:
    required: false
  add_to_test_requirements:
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --project
    - ${{ inputs.project }}
    - --pypi_version
    - ${{ inputs.pypi_version }}
    - --setup_cfg_filepath
    - ${{ inputs.setup_cfg_filepath }}
    - --meta_yaml_filepath
    - ${{ inputs.meta_yaml_filepath }}
    - --add_to_run_requirements
    - ${{ inputs.add_to_run_requirements }}
    - --add_to_test_requirements
    - ${{ inputs.add_to_test_requirements }}
branding:
  icon: 'align-center'
  color: 'blue'
